### ISSUE TITLE
安全提示：不要在public repo中包含密钥

### ISSUE THREAD

**Issue by Willqie** [dowhilefalse/Donation-Platform#30]
Cookie Secret被以明文方式写在了setting.py中，这是很不安全的。

另外，通过/api可以直接访问后台所有api，且似乎不需要验证。请注意实际部署版本的安全问题。

**Comment by gsw945** [comment]
- Cookie Secret服务器上正式情况下会改掉
- /api是有权限验证的，未登录情况就只有只读权限，大多是公开资源

**Comment by Willqie** [comment]
/api/users 可以无验证列出所有用户的手机号码

**Comment by Willqie** [comment]
你们的部署环境也没有关闭DEBUG模式
